FROM digitcombe/df-config-server-base:latest

# Install dev/build dependencies
RUN apt-get update && apt-get update -y

# Setup environment variable

# Run Unit and Integration Tests

# Build Application Artifacts

# Set defaults for entrypoint and command string

CMD ["java", "-jar", "df-config-server.jar"]

# docker build -t df-config-server-dev -f docker/dev/Dockerfile .
