spring:
  application:
    name: fruit-vegetables-api

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


server:
  port: 8081

logging:
  level:
    "liquibase": info
